import { AgentSkill } from "../../harness/index.ts";

export const AdaptiveStudyPlanSkill = AgentSkill.make({
  name: "adaptive-study-plan",
  description: "Diagnose uploaded syllabus materials and active knowledge gaps, then persist a prioritized study roadmap as a single note artifact.",
  content: [
    "# Adaptive study plan",
    "",
    "Use this skill when the student asks for:",
    "- a study plan, learning roadmap, study path, or syllabus diagnosis",
    "- a structured study note covering their uploaded materials",
    "- priorities, milestones, or a plan to master the temario",
    "",
    "Do NOT use this skill for a targeted quiz of past mistakes. That is `review-knowledge-gaps`.",
    "",
    "HARD RULES:",
    "- Create exactly ONE artifact this turn: a `note`. Never create a quiz or a test.",
    "- Never run `artifacts list` or `artifacts show`. The web app will render only the new note widget.",
    "- The checklist may mention a future quiz as a next action, but do not create that quiz now.",
    "",
    "Available CLI commands:",
    "- `materials list`: inspect the PDF library (ids, titles, page counts).",
    "- `knowledge gaps`: list active failed questions and misconceptions.",
    "- `knowledge summary`: high-level counts of active / reviewing / mastered topics.",
    "- `artifacts create '<json>'`: persist the roadmap as a `note`. Always wrap JSON in single quotes.",
    "",
    "Workflow:",
    "1. Run `materials list` first. Use titles and page counts to size the syllabus (do not invent page counts).",
    "2. Run `knowledge gaps` (and `knowledge summary` if useful) to detect weak points and current level.",
    "3. Draft a Spanish markdown roadmap with this structure:",
    "   - Diagnóstico: library coverage + active gaps (cite real topics/questions, never fabricate gaps).",
    "   - Fases de estudio: ordered milestones. Put active-gap topics first, then uncovered syllabus areas.",
    "   - Conceptos críticos: the 3–7 ideas the student must master, with a one-line why.",
    "   - Estimación de tiempo: rough ranges derived from page counts (e.g. short docs = one sitting; long docs = split phases). Do not fake precision.",
    "   - Checklist: concrete, checkable next actions (read pages X–Y, later take a 3-question quiz, review gap Z).",
    "4. Persist it with exactly one `artifacts create` as a note. Example:",
    "   `artifacts create '{\"kind\":\"note\",\"title\":\"Plan de estudio\",\"markdown\":\"# Plan de estudio\\n...\"}'`",
    "5. After a successful create, reply with only a brief one- or two-sentence presentation. The web app renders the note widget automatically. Do not dump the full markdown, JSON, or artifact id in chat.",
    "",
    "Fallback rules:",
    "- If the library is empty: still write a plan from active gaps (or a generic diagnostic plan) and invite the student to upload PDFs with the clip button.",
    "- If there are no gaps: sequence the materials by page count and conceptual dependency, and mention a diagnostic quiz in the checklist only.",
    "- Never skip `artifacts create`. The student asked for a saved study note, not only a chat explanation."
  ].join("\n")
});
