import { AgentSkill } from "../../harness/index.ts";

export const CreateStudyArtifactsSkill = AgentSkill.make({
  name: "create-study-artifacts",
  description: "Create and manage study artifacts: markdown notes, quizzes, tests, submissions, and graded attempts.",
  content: [
    "# Create study artifacts",
    "",
    "Use this skill when the user asks you to create study notes, quizzes, tests, or practice submissions.",
    "",
    "Artifacts are persisted study objects:",
    "- `note`: title plus markdown content. Notes are not submitted or graded.",
    "- `quiz`: title plus auto-gradable multiple-choice / true-false questions.",
    "- `test`: title plus questions. Tests may include multiple-choice, true-false, and short-answer questions.",
    "",
    "Generation rules:",
    "- Respect the exact number of questions requested by the student. If no number is given, use 3 for a quiz and 10 for a test.",
    "- The web interface automatically renders an interactive widget after `artifacts create` succeeds.",
    "- After creating an artifact, write only a brief one- or two-sentence presentation. Do not repeat questions, options, solutions, JSON, artifact IDs, or tell the student to answer in chat with Q1: A.",
    "",
    "Available CLI commands:",
    "- `artifacts list [note|quiz|test]`: list saved artifacts.",
    "- `artifacts show <artifactId>`: show an artifact JSON.",
    "- `artifacts create '<json>'`: create a note, quiz, or test from CreateArtifactInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts submit '<json>'`: submit answers for a quiz or test from SubmitAttemptInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts attempts [artifactId]`: list attempts.",
    "- `artifacts grade <attemptId>`: grade and persist a submitted attempt.",
    "",
    "CreateArtifactInput examples:",
    "- `artifacts create '{\"kind\":\"note\",\"title\":\"Derivatives summary\",\"markdown\":\"# Derivatives\\n...\"}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Basics quiz\",\"questions\":[{\"type\":\"true-false\",\"id\":\"q1\",\"prompt\":\"2+2=4\",\"correctAnswer\":true,\"explanation\":\"Basic arithmetic.\"}]}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Concept quiz\",\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"Which option is qualitative?\",\"options\":[{\"id\":\"qualitative\",\"text\":\"Qualitative\"},{\"id\":\"quantitative\",\"text\":\"Quantitative\"}],\"correctOptionId\":\"qualitative\",\"explanation\":\"Qualitative data describes qualities.\"}]}'`",
    "",
    "Multiple-choice question rules:",
    "- `options` must be objects, not strings: `{\"id\":\"a\",\"text\":\"Option text\"}`.",
    "- `correctOptionId` must exactly match one option `id`.",
    "",
    "SubmitAttemptInput example:",
    "- `artifacts submit '{\"artifactKind\":\"quiz\",\"artifactId\":\"<id>\",\"answers\":[{\"questionType\":\"true-false\",\"questionId\":\"q1\",\"answer\":true}]}'`",
    "",
    "Workflow:",
    "1. For artifacts based on uploaded materials, inspect the uploaded material first.",
    "2. Create a compact artifact that directly matches the user's request.",
    "3. When the artifact is based on an uploaded PDF, include `sourceMaterialId` with that material's id.",
    "4. Use unique stable question ids like `q1`, `q2`, `q3` within each artifact.",
    "5. For quizzes, prefer true-false and multiple-choice because grading is deterministic.",
    "6. When a user submits answers, save the attempt and then grade it."
  ].join("\n")
});
