import { AgentSkill } from "../../harness/index.ts";

export const ReviewKnowledgeGapsSkill = AgentSkill.make({
  name: "review-knowledge-gaps",
  description: "Inspect active knowledge gaps from past quizzes and generate one targeted reinforcement quiz from the materials where the student failed.",
  content: [
    "# Review Knowledge Gaps",
    "",
    "Use this skill when:",
    "- The student asks to rescue knowledge gaps, reinforce past failures, or generate a quiz from their weak points.",
    "- The student asks what to review or about their weak points.",
    "- You want to mark concepts as reviewing or mastered after explaining them.",
    "",
    "Do NOT use this skill for a full syllabus roadmap. That is `adaptive-study-plan`.",
    "",
    "HARD RULES:",
    "- Create exactly ONE new quiz this turn with a single `artifacts create`. Never create a second quiz, a test, or a note.",
    "- Never run `artifacts list` or `artifacts show`. Existing quizzes must not be reopened or recreated.",
    "- Never copy a failed question verbatim. Retrain the same misconception from a new angle.",
    "- Honor the requested question count exactly, with a hard maximum of 10 questions:",
    "  - 3, 6 or 10: that many questions. If there are fewer gaps, cover them from multiple angles; if there are more, pick the most critical.",
    "  - Never create more than 10 questions, even if there are more active gaps or the student asks for all of them.",
    "  - if the student did not specify a count, default to 3.",
    "",
    "Available CLI commands:",
    "- `knowledge gaps`: list active knowledge gaps with questions and explanations.",
    "- `knowledge summary`: get a concise overview of weak topics.",
    "- `knowledge review <gapId>`: mark a gap as currently reviewing.",
    "- `knowledge master <gapId>`: mark a gap as mastered after the student demonstrates understanding.",
    "- `materials list`: list uploaded PDFs and their ids.",
    "- `materials search <materialId> \"<concepto>\"`: locate pages that cover a failed concept (use quotes for multi-word queries).",
    "- `artifacts create '<json>'`: create the single focused quiz. Always wrap JSON in single quotes.",
    "",
    "Quiz example:",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Refuerzo: Art. 17 CE\",\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"¿Cuál es el plazo máximo ordinario de detención preventiva?\",\"options\":[{\"id\":\"a\",\"text\":\"24 horas\"},{\"id\":\"b\",\"text\":\"72 horas\"}],\"correctOptionId\":\"b\",\"explanation\":\"El art. 17.2 CE fija 72 horas.\"}]}'`",
    "",
    "Workflow:",
    "1. Always run `knowledge gaps` first (add `knowledge summary` if you need topic counts).",
    "2. If gaps exist and the student asked for rescue, reinforcement, or a targeted quiz:",
    "   a. Run `materials list` to obtain material ids.",
    "   b. Search a few representative failed concepts with `materials search <id> \"<concepto>\"` (do not search once per question). Cite those pages in explanations.",
    "   c. Create exactly one focused quiz with `artifacts create`. Use the requested question count; default 3 if none was specified.",
    "   d. Mark the targeted gaps with `knowledge review <gapId>`.",
    "   e. After a successful create, write only a brief one- or two-sentence presentation. Do not repeat questions, options, solutions, JSON, or artifact ids.",
    "3. If gaps exist but the student only asked what to review: pick the most critical topic, cite the specific question they failed, and explain the core concept clearly. Offer a reinforcement quiz as the next step; do not create it unless they asked.",
    "4. If no gaps exist: tell the student their profile is clean and offer a general diagnostic quiz from their uploaded materials. Create that diagnostic quiz only if they accept. Do not invent fake gaps.",
    "5. When the student confirms understanding or answers the reinforcement quiz correctly, run `knowledge master <gapId>`.",
    "",
    "Fallback rules:",
    "- If the library is empty, still create the one reinforcement quiz from the gap explanations and invite the student to upload PDFs."
  ].join("\n")
});
